menu: # To remove a menu, just leave the value blank.
  home: Home
  projects: Projects
  services: 
  prices: 
  blog: Blog
  about: About
  contact:

#show the subscribe area
#default false
subscribe: false

#default featured image for posts
featured: "/img/default-new-blog.jpg"

#default background image for posts
background: "/img/default-background.jpg"
